name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install deps
        run: npm install --prefer-offline --no-audit --no-fund
      - name: Configure git user for gh-pages
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Build & Deploy
        # Use the Actions-provided GITHUB_TOKEN in the repository URL so gh-pages
        # can push back to the repo non-interactively from the runner.
        run: npx gh-pages -d . --repo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
